name: Deploy to S3 (OIDC)

on:
  push:
    branches: [ main ]

permissions:
  id-token: write  # required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::358238714507:role/TESTING-PRACTICE
          aws-region: us-east-1

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://ravi-website-bucket-name --delete --exclude ".git/*" --exclude ".github/*"
